version: "3.9"

services:
  database: #ESSE É O NOME DO SERVICE QUE DEVE ESTAR NO ARQUIVO DE CRIAÇÃO DE CONEXÃO
    image: postgres
    container_name: typeorm_db
    restart: always
    ports: 
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=diego
      - POSTGRES_DB=typeorm
    volumes:
      - pgdata:/data/postgres


  app:
    build: .
    container_name: typeorm
    restart: always
    ports: 
      - 3333:3333
      - 9229:9229 #debug port
    volumes: 
      - .:/usr/app


volumes:
  pgdata:
    driver: local